Feature: 
      Login with community Matrimony & find image not available issue homepage

Scenario Outline: registration to direct community

Given user have to enter matrimony domain all name "<Domainname>"

Examples: 
      |Domainname| 
      |https://www.40plusmatrimony.com/ | 
      |https://www.Divorceematrimony.com/ |
 |https://www.Christianmatrimony.com/ |
 |https://www.Muslimmatrimony.com/ |
 |https://www.Brahminmatrimony.com/ | 
|https://www.Nairmatrimony.com/ |
 |https://www.Ezhavamatrimony.com/ |
|https://www.Reddymatrimony.com/ |
|https://www.Vanniyarmatrimony.com/ |
|https://www.Scmatrimony.com/ |
|https://www.Nadarmatrimony.com/ |
|https://www.Vishwakarmamatrimony.com/ | 
|https://www.Lingayatmatrimony.com/ |
|https://www.Kammamatrimony.com/ |
 |https://www.Mudaliyarmatrimony.com/ |
|https://www.Kayasthamatrimony.com/ |
 |https://www.Doctorsmatrimony.com/ |
|https://www.Agarwalmatrimony.com/ |
|https://www.Iimiitmatrimony.com/ |
|https://www.Vellalarmatrimony.com/ |
             #|https://www.40plusmatrimony.com/ |       
#|https://www.96kulimarathamatrimony.com/ |
#|https://www.Addharmimatrimony.com/ |
#|https://www.Adidravidarmatrimony.com/ |
#|https://www.Agarwalmatrimony.com/ |
#|https://www.Agrimatrimony.com/ |
#|https://www.Ahommatrimony.com/ |
#|https://www.Ambalavasimatrimony.com/ |
#|https://www.Anavilmatrimony.com/ |
#|https://www.Anycastematrimony.com/ |
#|https://www.Arekatikamatrimony.com/ |
#|https://www.Aroramatrimony.com/ |
#|https://www.Arunthathiyarmatrimony.com/ |
#|https://www.Aryavysyamatrimony.com/ |
#|https://www.Audichyamatrimony.com/ |
#|https://www.Badagarmatrimony.com/ |
#|https://www.Baidyamatrimony.com/ |
#|https://www.Baishnabmatrimony.com/ |
#|https://www.Baishyamatrimony.com/ |
#|https://www.Balijamatrimony.com/ |
#|https://www.Banikmatrimony.com/ |
#|https://www.Baniyamatrimony.com/ |
#|https://www.Banjaramatrimony.com/ |
#|https://www.Baraimatrimony.com/ |
#|https://www.Barendramatrimony.com/ |
#|https://www.Barimatrimony.com/ |
#|https://www.Barujibimatrimony.com/ |
#|https://www.Bestamatrimony.com/ |
#|https://www.Bhandarimatrimony.com/ |
#|https://www.Bhatiamatrimony.com/ |
#|https://www.Bhatrajumatrimony.com/ |
#|https://www.Bhattmatrimony.com/ |
#|https://www.Bhavasarkshatriyamatrimony.com/ |
#|https://www.Bhovimatrimony.com/ |
#|https://www.Bhumiharmatrimony.com/ |
#|https://www.Billavamatrimony.com/ |
#|https://www.Boyermatrimony.com/ |
    #|https://www.Brahminmatrimony.com/ | 
#|https://www.Buddhistmatrimony.com/ | 
 #|https://www.Chambharmatrimony.com/ | 
 #|https://www.Chandravanshikaharmatrimony.com/ |
#|https://www.Chasamatrimony.com/ |
#|https://www.Chattadasrivaishnavamatrimony.com/ |
#|https://www.Chaudarymatrimony.com/ |
 #|https://www.Chaurasiamatrimony.com/ |
#|https://www.Chettiyarmatrimony.com/ |
#|https://www.Chhetrimatrimony.com/ |
 #|https://www.Chippolumatrimony.com/ |
 #|https://www.Christianmatrimony.com/ |
 #|https://www.Ckpmatrimony.com/ |
 #|https://www.Coorgmatrimony.com/ |
 #|https://www.Daivadnyamatrimony.com/ |
 #|https://www.Danuamatrimony.com/ |
 #|https://www.Defencematrimony.com/ |
 #|https://www.Deshasthamatrimony.com/ |
 #|https://www.Devadigamatrimony.com/ |
 #|https://www.Devangamatrimony.com/ |
 #|https://www.Devangkoshtimatrimony.com/ |
 #|https://www.Devendrarmatrimony.com/ |
 #|https://www.Dhangarmatrimony.com/ |
 #|https://www.Dheevaramatrimony.com/ |
 #|https://www.Dhimanmatrimony.com/ |
 #|https://www.Dhobamatrimony.com/ |
 #|https://www.Dhobimatrimony.com/ |
 #|https://www.Divorceematrimony.com/ |
 #|https://www.Doctorsmatrimony.com/ |
 #|https://www.Dravidamatrimony.com/ |
 #|https://www.Dumalmatrimony.com/ |
 #|https://www.Edigamatrimony.com/ |
 #|https://www.Ezhavamatrimony.com/ |
 #|https://www.Ezhuthachanmatrimony.com/ |
 #|https://www.Gabitmatrimony.com/ |
 #|https://www.Gandlamatrimony.com/ |
 #|https://www.Ganigamatrimony.com/ |
 #|https://www.Garhwalmatrimony.com/ |
 #|https://www.Gaurmatrimony.com/ |
 #|https://www.Gavalimatrimony.com/ |
 #|https://www.Gavaramatrimony.com/ |
 #|https://www.Ghisadimatrimony.com/ |
 #|https://www.Ghumarmatrimony.com/ |
 #|https://www.Goalamatrimony.com/ |
 #|https://www.Gomantakmatrimony.com/ |
 #|https://www.Gondhalimatrimony.com/ |
 #|https://www.Goudmatrimony.com/ |
 #|https://www.Goundermatrimony.com/ |
 #|https://www.Gowdamatrimony.com/ |
 #|https://www.Gramanimatrimony.com/ |
 #|https://www.Gudiamatrimony.com/ |
 #|https://www.Gujjarmatrimony.com/ |
 #|https://www.Guptamatrimony.com/ |
 #|https://www.Guptanmatrimony.com/ |
 #|https://www.Guravmatrimony.com/ |
 #|https://www.Gurjarmatrimony.com/ |
 #|https://www.Gurukkalmatrimony.com/ |
 #|https://www.Haluamatrimony.com/ |
 #|https://www.Havyakamatrimony.com/ |
#|https://www.Hoysalamatrimony.com/ |
 #|https://www.Hugarmatrimony.com/ |
 #|https://www.Iimiitmatrimony.com/ |
 #|https://www.Intercastematrimony.com/ |
 #|https://www.Iranimatrimony.com/ |
 #|https://www.Iyengarmatrimony.com/ |
 #|https://www.Iyermatrimony.com/ |
 #|https://www.Jainmatrimony.com/ |
 #|https://www.Jaiswalmatrimony.com/ |
 #|https://www.Jalarimatrimony.com/ |
 #|https://www.Jandramatrimony.com/ |
 #|https://www.Jangammatrimony.com/ |
 #|https://www.Jangidmatrimony.com/ |
 #|https://www.Jatavmatrimony.com/ |
#|https://www.Jatmatrimony.com/ |
 #|https://www.Jhaduamatrimony.com/ |
 #|https://www.Jogimatrimony.com/ |
#|https://www.Kacharamatrimony.com/ |
 #|https://www.Kadavapatelmatrimony.com/ |
 #|https://www.Kaibartamatrimony.com/ |
 #|https://www.Kalarmatrimony.com/ |
 #|https://www.Kalingamatrimony.com/ |
 #|https://www.Kalingavysyamatrimony.com/ |
 #|https://www.Kalitamatrimony.com/ |
 #|https://www.Kalwarmatrimony.com/ |
 #|https://www.Kambojmatrimony.com/ |
 #|https://www.Kammamatrimony.com/ |
 #|https://www.Kansarimatrimony.com/ |
 #|https://www.Kanyakubjmatrimony.com/ |
 #|https://www.Kapumatrimony.com/ |
 #|https://www.Karanamatrimony.com/ |
 #|https://www.Karhadematrimony.com/ |
 #|https://www.Karmakarmatrimony.com/ |
 #|https://www.Karuneegarmatrimony.com/ |
 #|https://www.Kasarmatrimony.com/ |
 #|https://www.Kashyapmatrimony.com/ |
 #|https://www.Katiyamatrimony.com/ |
 #|https://www.Kayasthamatrimony.com/ |
 #|https://www.Keralachristianmatrimony.com/ |
 #|https://www.Khandayatmatrimony.com/ |
 #|https://www.Khandelwalmatrimony.com/ |
 #|https://www.Kharwarmatrimony.com/ |
 #|https://www.Khatrimatrimony.com/ |
 #|https://www.Koirimatrimony.com/ |
 #|https://www.Kokanasthamarathamatrimony.com/ |
 #|https://www.Kokanasthamatrimony.com/ |
 #|https://www.Kolimatrimony.com/ |
 #|https://www.Konguvellalarmatrimony.com/ |
 #|https://www.Konkanimatrimony.com/ |
 #|https://www.Korimatrimony.com/ |
 #|https://www.Kotamatrimony.com/ |
 #|https://www.Kshatriyamatrimony.com/ |
 #|https://www.Kudumbimatrimony.com/ |
 #|https://www.Kulalarmatrimony.com/ |
 #|https://www.Kulalmatrimony.com/ |
 #|https://www.Kulinmatrimony.com/ |
 #|https://www.Kulitamatrimony.com/ |
 #|https://www.Kumaonimatrimony.com/ |
 #|https://www.Kumawatmatrimony.com/ |
 #|https://www.Kumbhakarmatrimony.com/ |
 #|https://www.Kumbharmatrimony.com/ |
 #|https://www.Kumharmatrimony.com/ |
 #|https://www.Kummarimatrimony.com/ |
 #|https://www.Kunbimatrimony.com/ |
 #|https://www.Kuravanmatrimony.com/ |
 #|https://www.Kurmikshatriyamatrimony.com/ |
 #|https://www.Kurmimatrimony.com/ |
 #|https://www.Kurubamatrimony.com/ |
 #|https://www.Kuruhinashettymatrimony.com/ |
 #|https://www.Kurumbarmatrimony.com/ |
 #|https://www.Lambanimatrimony.com/ |
 #|https://www.Levapatelmatrimony.com/ |
 #|https://www.Levapatilmatrimony.com/ |
#|https://www.Lingayatmatrimony.com/ |
 #|https://www.Lodhimatrimony.com/ |
 #|https://www.Lohanamatrimony.com/ |
 #|https://www.Lubanamatrimony.com/ |
 #|https://www.Madhvamatrimony.com/ |
 #|https://www.Madigamatrimony.com/ |
 #|https://www.Mahajanmatrimony.com/ |
 #|https://www.Maharmatrimony.com/ |
 #|https://www.Mahendramatrimony.com/ |
 #|https://www.Maheshwarimatrimony.com/ |
 #|https://www.Mahishyamatrimony.com/ |
 #|https://www.Maithilmatrimony.com/ |
 #|https://www.Malamatrimony.com/ |
 #|https://www.Malimatrimony.com/ |
 #|https://www.Mallamatrimony.com/ |
 #|https://www.Mangaloreanmatrimony.com/ |
 #|https://www.Manglikmatrimony.com/ |
 #|https://www.Manipurimatrimony.com/ |
 #|https://www.Mappilamatrimony.com/ |
 #|https://www.Marathamatrimony.com/ |
 #|https://www.Maruthuvarmatrimony.com/ |
 #|https://www.Matangmatrimony.com/ |
 #|https://www.Mathurmatrimony.com/ |
 #|https://www.Mazhabimatrimony.com/ |
 #|https://www.Meenamatrimony.com/ |
 #|https://www.Meenavarmatrimony.com/ |
 #|https://www.Mehramatrimony.com/ |
 #|https://www.Merudarjimatrimony.com/ |
 #|https://www.Mochimatrimony.com/ |
 #|https://www.Modakmatrimony.com/ |
 #|https://www.Modhmatrimony.com/ |
 #|https://www.Mogaveeramatrimony.com/ |
 #|https://www.Mudaliyarmatrimony.com/ |
#|https://www.Mudirajmatrimony.com/ |
 #|https://www.Munnurukapumatrimony.com/ |
 #|https://www.Muslimmatrimony.com/ |
 #|https://www.Muthurajamatrimony.com/ |
 #|https://www.Naagavamsammatrimony.com/ |
 #|https://www.Nadarmatrimony.com/ |
 #|https://www.Nagaralumatrimony.com/ |
 #|https://www.Nagarmatrimony.com/ |
 #|https://www.Naickermatrimony.com/ |
 #|https://www.Naidumatrimony.com/ |
 #|https://www.Naikmatrimony.com/ |
 #|https://www.Naimatrimony.com/ |
 #|https://www.Nairmatrimony.com/ |
 #|https://www.Namasudramatrimony.com/ |
 #|https://www.Nambiarmatrimony.com/ |
 #|https://www.Namboodirimatrimony.com/ |
 #|https://www.Napitmatrimony.com/ |
 #|https://www.Nayakamatrimony.com/ |
 #|https://www.Neelimatrimony.com/ |
 #|https://www.Nhavimatrimony.com/ |
 #|https://www.Niyogimatrimony.com/ |
 #|https://www.Oswalmatrimony.com/ |
 #|https://www.Otarimatrimony.com/ | 
 #|https://www.Padmasalimatrimony.com/ |
 #|https://www.Palmatrimony.com/ |
 #|https://www.Panchalmatrimony.com/ |
#|https://www.Pandamatrimony.com/ |
#|https://www.Panditmatrimony.com/ |
 #|https://www.Panickermatrimony.com/ |
 #|https://www.Parkavakulammatrimony.com/ |
 #|https://www.Partrajmatrimony.com/ |
 #|https://www.Pasimatrimony.com/ |
#|https://www.Paswanmatrimony.com/ |
 #|https://www.Patelmatrimony.com/ |
 #|https://www.Patnaikmatrimony.com/ |
#|https://www.Patramatrimony.com/ |
 #|https://www.Perikamatrimony.com/ |
 #|https://www.Pillaimatrimony.com/ |
 #|https://www.Porwalmatrimony.com/ |
 #|https://www.Prajapatimatrimony.com/ |
 #|https://www.Pushkarnamatrimony.com/ |
 #|https://www.Raigarmatrimony.com/ |
#|https://www.Rajakamatrimony.com/ |
#|https://www.Rajastanimatrimony.com/ |
 #|https://www.Rajbongshimatrimony.com/ |
 #|https://www.Rajputmatrimony.com/ |
 #|https://www.Ramdasiamatrimony.com/ |
 #|https://www.Ramgarhiamatrimony.com/ |
 #|https://www.Rarhimatrimony.com/ |
 #|https://www.Ravidasiamatrimony.com/ |
#|https://www.Rawatmatrimony.com/ |
 #|https://www.Reddymatrimony.com/ |
 #|https://www.Rellimatrimony.com/ |
 #|https://www.Rigvedimatrimony.com/ |
 #|https://www.Rudrajmatrimony.com/ |
 #|https://www.Sadgopematrimony.com/ |
 #|https://www.Sahamatrimony.com/ |
 #|https://www.Sahumatrimony.com/ |
 #|https://www.Sainimatrimony.com/ |
 #|https://www.Sakaldwipimatrimony.com/ |
#|https://www.Saliyamatrimony.com/ |
#|https://www.Sanadhyamatrimony.com/ |
 #|https://www.Sankethimatrimony.com/ |
#|https://www.Saraswatmatrimony.com/ |
 #|https://www.Saryupareenmatrimony.com/ |
#|https://www.Savjimatrimony.com/ |
 #|https://www.Scmatrimony.com/ |
 #|https://www.Senaithalaivarmatrimony.com/ |
 #|https://www.Sengunthamudaliyarmatrimony.com/ |
 #|https://www.Settibalijamatrimony.com/ |
 #|https://www.Shettymatrimony.com/ |
 #|https://www.Shimpimatrimony.com/ |
 #|https://www.Shivallimatrimony.com/ |
 #|https://www.Shrimalimatrimony.com/ |
 #|https://www.Sikhmatrimony.com/ |
 #|https://www.Skpmatrimony.com/ |
 #|https://www.Smarthamatrimony.com/ |
 #|https://www.Sonarmatrimony.com/ |
 #|https://www.Sourashtramatrimony.com/ |
 #|https://www.Sozhiyavellalarmatrimony.com/ |
 #|https://www.Sthanikamatrimony.com/ |
 #|https://www.Stmatrimony.com/ |
 #|https://www.Sugalimatrimony.com/ |
 #|https://www.Sunarimatrimony.com/ |
 #|https://www.Sundhimatrimony.com/ |
 #|https://www.Sutharmatrimony.com/ |
 #|https://www.Swakulasalimatrimony.com/ |
 #|https://www.Tambolimatrimony.com/ |
 #|https://www.Tantimatrimony.com/ |
#|https://www.Tantubaimatrimony.com/ |
 #|https://www.Telagamatrimony.com/ |
 #|https://www.Telimatrimony.com/ |
 #|https://www.Thakkarmatrimony.com/ |
 #|https://www.Thakurmatrimony.com/ |
 #|https://www.Thevarmatrimony.com/ |
 #|https://www.Thigalamatrimony.com/ |
 #|https://www.Thiyyamatrimony.com/ |
 #|https://www.Tilimatrimony.com/ |
 #|https://www.Togatamatrimony.com/ |
 #|https://www.Tonkkshatriyamatrimony.com/ |
 #|https://www.Turupukapumatrimony.com/ |
 #|https://www.Tyagimatrimony.com/ |
 #|https://www.Upparamatrimony.com/ |
 #|https://www.Ursmatrimony.com/ |
 #|https://www.Vadabalijamatrimony.com/ |
 #|https://www.Vadderamatrimony.com/ |
 #|https://www.Vaidikimatrimony.com/ |
 #|https://www.Vaishmatrimony.com/ |
 #|https://www.Vaishnavamatrimony.com/ |
 #|https://www.Vaishnavmatrimony.com/ |
 #|https://www.Vaishyamatrimony.com/ |
 #|https://www.Vaishyavanimatrimony.com/ |
 #|https://www.Valluvanmatrimony.com/ |
 #|https://www.Valmikimatrimony.com/ |
 #|https://www.Vaniamatrimony.com/ |
 #|https://www.Vaniyamatrimony.com/ |
 #|https://www.Vanjaramatrimony.com/ |
 #|https://www.Vanjarimatrimony.com/ |
 #|https://www.Vankarmatrimony.com/ |
 #|https://www.Vannarmatrimony.com/ |
 #|https://www.Vanniyarmatrimony.com/ |
 #|https://www.Variarmatrimony.com/ |
 #|https://www.Veerashaivamatrimony.com/ |
 #|https://www.Velaanmatrimony.com/ |
 #|https://www.Velamanaidumatrimony.com/ |
 #|https://www.Velanadumatrimony.com/ |
 #|https://www.Vellalarmatrimony.com/ |
#|https://www.Veluthedathunairmatrimony.com/ |
#|https://www.Vettuvagoundermatrimony.com/ |
#|https://www.Vilakkithalanairmatrimony.com/ |  
#|https://www.Vishwakarmamatrimony.com/ | 
#|https://www.Viswabrahminmatrimony.com/ | 
#|https://www.Vokkaligamatrimony.com/ | 
#|https://www.Vyasmatrimony.com/ | 
#|https://www.Vysyamatrimony.com/ |
#|https://www.Yadavmatrimony.com/ |
#|https://www.Yellapumatrimony.com/ |